server:
  port: 8080

file:
  upload-dir: backend/src/main/resources/static/uploads

spring:
  application:
    name: warehouse-system
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
  jackson:
    time-zone: UTC

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs

jwt:
  secret: WarehouseOsJwtSecretKey2024VeryLongSecretForHmacSha256Algorithm
  access-token-expiration: 1800000
  refresh-token-expiration: 604800000
